### ISSUE TITLE
Store the last scanned value

### ISSUE THREAD

**Issue by safiulbari** [aniruddha-adhikary/mrt-buddy#10]
It's a bit issue. It didn't store the last scanned value. I need to re-scan to know. It should store the last scanned value and transaction history.

![fix_needed](https://github.com/user-attachments/assets/3cf215a5-a3fb-4254-9dab-de8bd6b15971)

**Comment by Barury797** [comment]
Users can get confused by seeing balance appearing even before they scan the card. While it is a helpful feature, it will just confuse people.
