### ISSUE TITLE
Updating the app within the app

### ISSUE THREAD

**Issue by alaminsoyaib** [aniruddha-adhikary/mrt-buddy#12]
Add an update app popup so existing users who have installed the app will know there is a new release available and can download it within the app.

**Comment by aniruddha-adhikary** [comment]
Perhaps we should go Play Store?

**Comment by alaminsoyaib** [comment]
Great 🎉

**Comment by kazimmt** [comment]
Send an "Update available! Please update your app" notification at least

**Comment by aniruddha-adhikary** [comment]
@kazimmt That's a good idea.

I suppose what worries me is user trust. Like currently there is no internet access for the app. A good assurity that data isn't being sold or collected.

<img width="938" alt="Screenshot 2024-11-04 at 4 50 27 PM" src="https://github.com/user-attachments/assets/b2c64005-9910-4a2e-8bac-a89743691188">


I am adding the WhatsApp Channel link to announce updates... But what are your thoughts?

**Comment by rahat14** [comment]
@aniruddha-adhikary  we can check for the release via GitHub API and can hyper link the user to the git hub page from the app  ?

**Comment by aniruddha-adhikary** [comment]
We are on F Droid, Play Store Beta and App Store. So marking this as redundant. Thank you!
