### ISSUE TITLE
fix: Workflow

### ISSUE THREAD

**Issue by hmasum52** [aniruddha-adhikary/mrt-buddy#20]
Workflow fails to create a release if there a release tag exists with same name! I am working to fix this!

**Comment by aniruddha-adhikary** [comment]
Thank you!!!

**Comment by hmasum52** [comment]
@aniruddha-adhikary After some investigation I found that the error message "Resource not accessible by integration" when using the `actions/create-release@v1` GitHub Action typically indicates a permissions issue with the GitHub token being utilized in the workflow. 

According to the [documentation](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#permissions), we can use permissions to modify the default permissions granted to the GITHUB_TOKEN, adding or removing access as required, so that you only allow the minimum required access.

I am creating a PR with content write permissions.
