### ISSUE TITLE
Basic NFC reader feature , No api integrated!

### ISSUE THREAD

**Issue by Syed-Bipul-Rahman** [aniruddha-adhikary/mrt-buddy#3]
### **Basic NFC Reader Feature - No API Integration**

The developer has implemented only a basic NFC reader feature to read NFC card information. Unfortunately, this misleads users into believing the app provides accurate MRT pass data. It is important to note that MRT pass data is securely stored on a server.

After reviewing the app’s source code, I found no implementation of any API to fetch real data from the server. Instead, the app merely reads the NFC data and displays arbitrary values to the user. MRT and Rapid passes are specialized NFC cards that only contain the card number, while critical information, such as card balance, is stored server-side. To display genuine data from the server, proper API integration is required.

**Comment by aniruddha-adhikary** [comment]
@Syed-Bipul-Rahman Please do study up on Card-Based Accounting systems and FeliCa. Cheers mate.

**Comment by Syed-Bipul-Rahman** [comment]
> @Syed-Bipul-Rahman Please do study up on Card-Based Accounting systems and FeliCa. Cheers mate.

Thank you for your response regarding my issue. I appreciate your guidance and the opportunity to learn more about Card-Based Accounting systems and the FeliCa NFC system.

After conducting further research, **I realize that my understanding of the NFC data and its integration with server-side systems was incorrect.** I apologize for any confusion or frustration my previous comments may have caused.

I value the effort and expertise that you have put into the project, and I look forward to contributing positively to the discussion moving forward.
