### ISSUE TITLE
App shows NFC is turned off but my device doesn't support NFC

### ISSUE THREAD

**Issue by shuvo1997** [aniruddha-adhikary/mrt-buddy#32]
After Opening the app:
![Media (1)](https://github.com/user-attachments/assets/0cf0f9d5-9499-4572-9aca-406a784bc0af)

Device Name: POCO X3
Android: 12

**Comment by aniruddha-adhikary** [comment]
I did verify that this is indeed the case. Confirmed bug. Thanks for reporting.

**Comment by Zamiul-rashid** [comment]
I would like to work on this issue / bug

**Comment by aniruddha-adhikary** [comment]
@Zamiul-rashid Please go ahead! I am assigning this card

**Comment by Zamiul-rashid** [comment]
I worked on this and put in a PR ..

**Comment by aniruddha-adhikary** [comment]
Should be fixed! Please reopen if issue persists
