### ISSUE TITLE
⚠️ Create Contribution guideline ASAP

### ISSUE THREAD

**Issue by hmasum52** [aniruddha-adhikary/mrt-buddy#34]
As a lot of people are contributing to this branch a contribution guideline will help keep the codebase clean!

**Comment by aniruddha-adhikary** [comment]
Thanks for pointing this out. I indeed overlooked this part. I'll put a non comprehensive basic one out first.

**Comment by Zamiul-rashid** [comment]
Im on it assign it to me, I got what I need to write now..
