### ISSUE TITLE
Credits for Contributors

### ISSUE THREAD

**Issue by aniruddha-adhikary** [aniruddha-adhikary/mrt-buddy#36]
MRT Buddy is no longer made by Ani only, so many amazing new contributors joined us! We need to credit them all.

I'm thinking of a simple one.

The list of contributors should be on our GitHub pages website. (I.e, gh-pages branch of this repo). And the app could just launch the browser when users click contributors button or footer. 

I want to make sure that this is done before the 0.0.7 release is out!

**Comment by hmasum52** [comment]
You can add list of the contributors at the bottom of the README as well! 
Here is how you can do this https://github.com/all-contributors/all-contributors

**Comment by aniruddha-adhikary** [comment]
Yeet we have a contributors page and the android app now points to the contributors page!

**Comment by hmasum52** [comment]
@aniruddha-adhikary are you doing that manually? I think currently the contributors page misses some contributors. You can automate it using [allcontributors](https://allcontributors.org/docs/en/bot/overview) bot!

**Comment by aniruddha-adhikary** [comment]
Ah I wrote a Python script lol
