### ISSUE TITLE
The website is kinda basic

### ISSUE THREAD

**Issue by aniruddha-adhikary** [aniruddha-adhikary/mrt-buddy#40]
Anyone has any good design ideas about the website? 

https://mrtbuddy.com

`gh-pages` branch of this repo.

**Comment by Nafisarkar** [comment]
https://www.cursor.com what do you think about something similar to this? 🙄

**Comment by mihf05** [comment]
https://legendary-marzipan-68df0e.netlify.app/
@aniruddha-adhikary   is it ok

**Comment by aniruddha-adhikary** [comment]
Hell yeah this is DOPE. 

Let's remove the testimonial and perhaps use the real screenshot from the correct app!

This looks really clean.

Could we also do a similar theme for the contributors page

**Comment by enamulkhanbd** [comment]
I'm a UX/UI Designer, and I’d love to contribute as well. @aniruddha-adhikary aniruddha-adhikary, if you could share some thoughts, it would be great and help me design even better.
