### ISSUE TITLE
I have already completed creating a website for MRT buddy.  


### ISSUE THREAD

**Issue by mihf05** [aniruddha-adhikary/mrt-buddy#50]
Should I pull request it now?  Check the website and code first - https://mrt-buddy-web.vercel.app/
https://github.com/mihf05/mrt-buddy-web 
@aniruddha-adhikary 
@hmasum52

**Comment by aniruddha-adhikary** [comment]
Excellent work @mihf05 

Looks dope. Please do PR. Just make sure that the new privacy policy page is included! 

Also, the icons are bit... um... misleading. Could we use a simpler text menu here?

<img width="315" alt="Screenshot 2024-11-07 at 12 35 01 AM" src="https://github.com/user-attachments/assets/f0cd7eb4-bca1-4e27-a56c-065d8075f3a7">

**Comment by mihf05** [comment]
#52  before merging the pull request, visit the live website - https://[mrt-buddy-web.vercel.app](https://mrt-buddy-web.vercel.app/)
