### ISSUE TITLE
Nfc one time card

### ISSUE THREAD

**Issue by alaminsoyaib** [aniruddha-adhikary/mrt-buddy#6]
(_if possible_) contact with MRT and create a one time card system which could be paid using bkash, so that persons who have nfc can buy ticket from mobile and won't need to take card ( even that's a issue recently broadcasted in media that large number of people don't return the card ) thus this will reduce the pressure on vending machine and make the meteo more convenient...

**Comment by aniruddha-adhikary** [comment]
@alaminsoyaib, this could be a great idea - but this should be raised with DMTCL directly. We as community citizen developers do not have much to contribute in this!

Appreciate your thoughts and ideas man.

**Comment by NRSHAOWN** [comment]
Yes
