### ISSUE TITLE
Dark mode for Website 

### ISSUE THREAD

**Issue by Zamiul-rashid** [aniruddha-adhikary/mrt-buddy#62]
We can work on adding darkmode for the website that would bring some quality of life improvements.

**Comment by anikbsmrstucse** [comment]
i was reviewing your gh-pages-news branch, and that branch already start landing page development with next.js technology. is there any chance to contribute to the running website, implementing dark mode feature?

**Comment by Zamiul-rashid** [comment]
I think someones already working on it.

**Comment by anikbsmrstucse** [comment]
if you give me permission I will do it.

**Comment by anikbsmrstucse** [comment]
https://jmp.sh/s/MzzCyHFmOG4REHJzFkaT
 here is the dark mode glimps.is it ok?

**Comment by aniruddha-adhikary** [comment]
@anikbsmrstucse YO MAN send a PR

**Comment by anikbsmrstucse** [comment]
Sir I am doing PR request for dark mode
check it,when you are avaliable

**Comment by Eniamza** [comment]
This looks extremely good.

**Comment by anikbsmrstucse** [comment]
Thanks a lot sir❤
