### ISSUE TITLE
Wrong fare shows

### ISSUE THREAD

**Issue by rr-uchchash360** [aniruddha-adhikary/mrt-buddy#73]
![IMG_22ECE15DA2EE-1](https://github.com/user-attachments/assets/a50ed223-b348-4a75-8070-c0499784c32c)
![IMG_22ECE15DA2EE-2](https://github.com/user-attachments/assets/5326e786-4f33-45fe-8678-02f845b7d903)

Karwan Bazar to Bangladesh Secretariat fare is BDT 18 (single ticket fare is 20). But this shows BDT 27 (single ticket fare is 30)

You may use [this tool](https://dhakametro.online/en/fare) to know the fare.

**Comment by aniruddha-adhikary** [comment]
Acknowledged! Thanks for reporting this @rr-uchchash360

**Comment by aniruddha-adhikary** [comment]
Fixed in v0.0.10

**Comment by rahat14** [comment]
@rr-uchchash360  can u confirm this bug is fixed or not on v0.0.10

**Comment by rr-uchchash360** [comment]
yes, @rahat14. it's fixed.
