### ISSUE TITLE
wrong fare in fare calculator (ios)

### ISSUE THREAD

**Issue by mrzfahad** [aniruddha-adhikary/mrt-buddy#76]
ios version: 0.0.9

list of wrong fares (from motijheel)

1. Motijheel to Shewrapara shows 54, actual 45
2. Motijheel to Kazipara shows 63, actual 54
3. Motijheel to Mirpur 10 shows 63, actual 54
4. Motijheel to Mirpur 11 shows 72, actual 63
5. Motijheel to Uttara South shows 90, actual 81
6. Motijheel to Uttara Center shows 90, actual 81

**Comment by aniruddha-adhikary** [comment]
@mrzfahad Thank you so much for reporting this. We have submitted a fix to Apple and it should be fixed within 24 hours. I will update here once fixed.

**Comment by mrzfahad** [comment]
thanks, just got the update. version 0.0.10
