### ISSUE TITLE
Balance Highlighter

### ISSUE THREAD

**Issue by malikaraf** [aniruddha-adhikary/mrt-buddy#85]
![suggestion](https://github.com/user-attachments/assets/ae3c0baf-11bc-474d-8dff-948384b90f68)

A feature where the amount shown on the balance will be highlighted **red**. It can be something the user chooses by themselves(any amount to signify that the account is low on cash) or we can set a ceiling. This can be used to  notify the user about their balances running low. We can also add an alert notification everytime the user opens the app if their balance is low. I have attached a picture to visualize my suggestion

**Comment by aniruddha-adhikary** [comment]
Thank you for the suggestion @malikaraf! @Zamiul-rashid has implemented something similar. Should roll out in the next release!
