### ISSUE TITLE
bug: App unexpectedly closes when navigating back

### ISSUE THREAD

**Issue by Mahmud0808** [aniruddha-adhikary/mrt-buddy#90]
On any screen, using the navigation button or swipe gesture to go back causes the app to exit instead of returning to the previous screen. For example: Open Source Licenses screen, Transactions list screen.

Platform: Android

**Comment by aniruddha-adhikary** [comment]
Thanks for filing this, confirming as a bug

**Comment by aniruddha-adhikary** [comment]
This has been fixed.
