### ISSUE TITLE
Bug / Improvement Suggestion: No way to check balance from clicking on a saved card.

### ISSUE THREAD

**Issue by touhidurrr** [aniruddha-adhikary/mrt-buddy#95]
When you click on a saved card, transactions history is shown, but no way to check the balance of a saved card. This might me a hassle for multiple card holders.

Also a question: Does this App support Rapid Pass also?

**Comment by aniruddha-adhikary** [comment]
@touhidurrr Thanks for the suggestion. We will look into it.

Also yes, it supports Rapid Pass.

**Comment by aniruddha-adhikary** [comment]
Fixed in v0.0.21
