### ISSUE TITLE
Screen stack not cleared 

### ISSUE THREAD

**Issue by mimtiaze** [aniruddha-adhikary/mrt-buddy#96]
When I have navigate many screens, and attemp to close the app, it rewind every screen I visited, this mean stack of screens is not cleared when entering new screen.

**Comment by aniruddha-adhikary** [comment]
@mimtiaze Which version are you on?

**Comment by aniruddha-adhikary** [comment]
@mimtiaze Is it possible to share a screen recording with us?

**Comment by mimtiaze** [comment]
Sure, give me a moment

**Comment by mimtiaze** [comment]
https://github.com/user-attachments/assets/10e2daf8-203a-4087-af13-740806b1e80c

**Comment by aniruddha-adhikary** [comment]
Thank you @mimtiaze !

**Comment by mimtiaze** [comment]
This issue has been solved in v0.0.21
Thanks @aniruddha-adhikary
